# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30cc852c3717033f06f916bdab8aef744e585003b9b5537cf44daf893dbb6f3387722474d96efe81f85034cf51fd87dbcb9af1e77e9ed38b2a4060b319f51b1b

test:
  secret_key_base: 3579768c176897e7f53214a4f2f9c0a5397312f29dcb4ccc39230f8ca0f757f2bbd3a05e4195c7b45835790d708822f62fc1ee3e8c8aa01ef8c8d93214d8f24f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
